/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;




/**
 *
 * @author AMAN KUMAR
 */
public class AddProduct extends javax.swing.JFrame {

    String filename = null;
    byte[] person_image=null; //change name into product_image
    
    String user="root";
    String url="jdbc:mysql://localhost:3306/auction";
    String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    
    String userid="";
    void userid(String user)
    {
        userid=user;
        
    }
    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jCalendarTheme1 = new com.toedter.plaf.JCalendarTheme();
        jCalendarDemo1 = new com.toedter.calendar.demo.JCalendarDemo();
        jDateChooserCellEditor1 = new com.toedter.calendar.JDateChooserCellEditor();
        jDayChooserBeanInfo1 = new com.toedter.calendar.JDayChooserBeanInfo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Pid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pbrand = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pinfo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Pamount = new javax.swing.JTextField();
        btnImage = new javax.swing.JToggleButton();
        AddProduct = new javax.swing.JToggleButton();
        lbl_img = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        time_end = new com.toedter.calendar.JSpinnerDateEditor();
        time_start = new com.toedter.calendar.JSpinnerDateEditor();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jCalendarDemo1Layout = new javax.swing.GroupLayout(jCalendarDemo1.getContentPane());
        jCalendarDemo1.getContentPane().setLayout(jCalendarDemo1Layout);
        jCalendarDemo1Layout.setHorizontalGroup(
            jCalendarDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jCalendarDemo1Layout.setVerticalGroup(
            jCalendarDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Product Category");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Grocery", "Furniture", "Stationary", "Textiles", "Jewelry", "Sports" }));
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Product Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));
        getContentPane().add(Pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Product Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));
        getContentPane().add(Pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 272, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Brand");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        Pbrand.setMinimumSize(new java.awt.Dimension(64, 30));
        getContentPane().add(Pbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Product Information");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        Pinfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinfoActionPerformed(evt);
            }
        });
        getContentPane().add(Pinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 200, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        Pamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PamountActionPerformed(evt);
            }
        });
        getContentPane().add(Pamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 110, 30));

        btnImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnImage.setText("Add Image");
        btnImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImageMouseClicked(evt);
            }
        });
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, -1, -1));

        AddProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddProduct.setText("Add Product");
        AddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductMouseClicked(evt);
            }
        });
        getContentPane().add(AddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, -1, -1));

        lbl_img.setText(".");
        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 140, 170));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Start Time&Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, 19));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("End Time&Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        jToggleButton1.setText("Back");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, -1, -1));
        getContentPane().add(time_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));
        getContentPane().add(time_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_3_20_33.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinfoActionPerformed

    private void PamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PamountActionPerformed

    private void AddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductMouseClicked
        
       try {
            // TODO add your handling code here:
        
            con = DriverManager.getConnection(url,user,pass);
            
            String sql = "insert into product values(?,?,?,?,?,?,?,?,?,?,?)";   
            PreparedStatement st=(PreparedStatement)con.prepareStatement(sql);
            st.setString(1,(String)category.getSelectedItem());
            st.setString(2,(String)Pid.getText());
            st.setString(3, (String)Pname.getText());
            st.setString(4, (String)Pbrand.getText());
            st.setString(5, (String)Pamount.getText());
            st.setString(6,(String)Pinfo.getText());
            st.setBytes(7, person_image);
            st.setString(8,userid);
            st.setString(9,time_start.getValue().toString());
            st.setString(10,time_end.getValue().toString());
            st.setString(11,"0");
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Product Added Successfully");
            con.close();
           
            
            
        } 
        
        catch (SQLException e) {
                   e.printStackTrace();

        } 
    }//GEN-LAST:event_AddProductMouseClicked

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
     
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon= new ImageIcon( new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(imageIcon);
        try{
            File image=new File(filename);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;)
            {
                bos.write(buf,0,readNum);
            }
            person_image = bos.toByteArray();
            
        }
        catch(Exception e)
        {
                                    JOptionPane.showMessageDialog(null, e);

                                    
        }
        
        
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImageMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
          Seller sf=new Seller();
            sf.userid(userid);
                        sf.setVisible(true);
                        this.dispose();
        
    }//GEN-LAST:event_jToggleButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AddProduct;
    private javax.swing.JTextField Pamount;
    private javax.swing.JTextField Pbrand;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pinfo;
    private javax.swing.JTextField Pname;
    private javax.swing.JToggleButton btnImage;
    private javax.swing.JComboBox<String> category;
    private com.toedter.calendar.demo.JCalendarDemo jCalendarDemo1;
    private com.toedter.plaf.JCalendarTheme jCalendarTheme1;
    private com.toedter.calendar.JDateChooserCellEditor jDateChooserCellEditor1;
    private com.toedter.calendar.JDayChooserBeanInfo jDayChooserBeanInfo1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_img;
    private com.toedter.calendar.JSpinnerDateEditor time_end;
    private com.toedter.calendar.JSpinnerDateEditor time_start;
    // End of variables declaration//GEN-END:variables

    //byte[] img=
}
