/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;


import com.mysql.cj.xdevapi.Statement;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author AMAN KUMAR
 */
public class Bidder_Dashboard extends javax.swing.JFrame {
  String user="root";
    String url="jdbc:mysql://localhost:3306/auction";
    String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    
    //DefaultTableModel  model;
    
    void userid(String user)
    {
        UserId1.setText(user);
        
    }
    /**
     * Creates new form Bidder_Dashboard
     */
    public Bidder_Dashboard() {
        initComponents();
        show_product();
    }

    public void search(String str)
    {
        DefaultTableModel model = (DefaultTableModel)product_table.getModel();
        TableRowSorter<DefaultTableModel> trs= new TableRowSorter<>(model);
        product_table.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    public ArrayList<Product_Bid> productList(){
        ArrayList<Product_Bid> productList= new ArrayList<>();
        try{
            
              con = DriverManager.getConnection(url,user,pass);
            
          String sql = "Select * from product";   
            PreparedStatement st=(PreparedStatement)con.prepareStatement(sql);
           //Statement stmt=(Statement) con.createStatement();
           rs= st.executeQuery(sql);    
          
           Product_Bid product;
           while(rs.next())
           {
               product =new Product_Bid(rs.getString("Category"),rs.getString("ProductId"),rs.getString("ProductName"),rs.getString("Brand"),rs.getString("ProductInformation"),rs.getString("time_end"));
               productList.add(product);
           }
            con.close();
            
        }
        catch(Exception e)
        {
                        JOptionPane.showMessageDialog(null,e);
        }
        return productList;
    } 
    
    public void show_product()
    {
        ArrayList<Product_Bid> list = productList();
        DefaultTableModel model= (DefaultTableModel)product_table.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<list.size();i++)
        {
             //Getting end time from database
                String time = list.get(i).gettimeend();
                String timesplit[] = time.split(" ");
                String EndTime = timesplit[5]+"/"+"04"+"/"+timesplit[2]+" "+timesplit[3];
                
                //Getting current time
                String DATE_FORMAT_NOW = "yyyy/MM/dd HH:mm:ss";
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
                String curTime = sdf.format(cal.getTime());
            
                DateTimeFormatter f = DateTimeFormatter.ofPattern( "uuuu/MM/dd HH:mm:ss" );
                LocalDateTime start = LocalDateTime.parse( curTime , f ) ;
                LocalDateTime stop = LocalDateTime.parse( EndTime , f ) ;
                boolean isBefore = start.isBefore( stop ) ;
                
                //agar time over ho jaye
                if(isBefore)
                {
                    row[0]=list.get(i).getCategory();
                   row[1]=list.get(i).getProductId();
                   row[2]=list.get(i).getProductName();
                   row[3]=list.get(i).getBrand();
                   row[4]=list.get(i).getProductInfo();
                    model.addRow(row);
                }
                
            
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jToggleButton3 = new javax.swing.JToggleButton();
        UserId = new javax.swing.JLabel();
        bidding_state = new javax.swing.JToggleButton();
        view_product = new javax.swing.JToggleButton();
        search_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UserId1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bidder Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, 47));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("UserId");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 50, -1));

        jToggleButton1.setText("Edit Profile");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 120, -1));

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Product ID", "Product Name", "Brand", "Product Information"
            }
        ));
        product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(product_table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 600, 243));

        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton3.setText("Logout");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, -1, -1));
        getContentPane().add(UserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1291, 20, 51, -1));

        bidding_state.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bidding_state.setText("Bidding Status");
        bidding_state.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bidding_stateMouseClicked(evt);
            }
        });
        bidding_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidding_stateActionPerformed(evt);
            }
        });
        getContentPane().add(bidding_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));

        view_product.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        view_product.setText("View Product");
        view_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_productMouseClicked(evt);
            }
        });
        getContentPane().add(view_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, -1, -1));

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_fieldKeyReleased(evt);
            }
        });
        getContentPane().add(search_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 89, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Search");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        UserId1.setText(".");
        getContentPane().add(UserId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_3_5_55.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
               
                       Bidder_Edit_Profile ep=new Bidder_Edit_Profile();  
                        ep.setVisible(true);
                        try {
           
            con = DriverManager.getConnection(url,user,pass);
           
             st = con.prepareStatement("select * from bidder where UserId='"+UserId1.getText()+"'");
             rs = (java.sql.ResultSet) st.executeQuery();
          
            String names="";
               String email="";
               String phone="";
               String password="";
           while(rs.next())
           {
               names = rs.getString("Name");
               email = rs.getString("Email");
                phone = rs.getString("Phone");
               password = rs.getString("Password");
               
               
           }
           
            
            ep.usersdata(UserId1.getText(),names,email,phone,password);
                        this.dispose();
    }               catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void bidding_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidding_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidding_stateActionPerformed

    private void view_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_productMouseClicked
        View_Product_Bid obj=new View_Product_Bid();
      
        int selectedRow = product_table.getSelectedRow(); // get selected row index
         DefaultTableModel model = (DefaultTableModel) product_table.getModel(); // get table model
        String id = model.getValueAt(selectedRow, 1).toString();
        obj.setVisible(true);
        try{
            con = DriverManager.getConnection(url,user,pass);
           
             st = con.prepareStatement("select * from product where ProductId='"+id+"'");
             rs = (java.sql.ResultSet) st.executeQuery();
         
              String category="";
               String product_id ="";
               String product_name="";
               String price="";
               String endtimetoshow="";
               String description="";
               String seller_id="";
               Image im = null;
           while(rs.next())
           {
               category = rs.getString("Category");
               product_id = rs.getString("ProductId");
               product_name=rs.getString("ProductName");
               price=rs.getString("Amount");
               description=rs.getString("ProductInformation");
               seller_id=rs.getString("Seller_Id");
               endtimetoshow=rs.getString("time_end");
                byte[] img= rs.getBytes("ProductImage");
                ImageIcon image = new ImageIcon(img);
                im = image.getImage();
           }
             
        obj.productdata(category, product_id, product_name, price, description,im,UserId1.getText(),seller_id,endtimetoshow);
        this.dispose();
        }
        catch(Exception ex)
        {
                        JOptionPane.showMessageDialog(null,ex );

        }
    }//GEN-LAST:event_view_productMouseClicked

    private void product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_product_tableMouseClicked

    private void bidding_stateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bidding_stateMouseClicked
         Bidding_Status_Bidder sf=new Bidding_Status_Bidder();
                       
                   
            sf.userid(UserId1.getText());
                       
                        sf.setVisible(true);
                       
                        this.dispose();
    }//GEN-LAST:event_bidding_stateMouseClicked

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void search_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyReleased
        String searchstring =search_field.getText();
        search(searchstring);  
    }//GEN-LAST:event_search_fieldKeyReleased

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        // TODO add your handling code here:
        
                        new Login().setVisible(true);
                        this.dispose();
    }//GEN-LAST:event_jToggleButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bidder_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bidder_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bidder_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bidder_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bidder_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserId;
    private javax.swing.JLabel UserId1;
    private javax.swing.JToggleButton bidding_state;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTable product_table;
    private javax.swing.JTextField search_field;
    private javax.swing.JToggleButton view_product;
    // End of variables declaration//GEN-END:variables
}
