/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;

import com.mysql.cj.xdevapi.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.*;
/**
 *
 * @author AMAN KUMAR
 */
public class Login extends javax.swing.JFrame {

    String user="root";
    String url="jdbc:mysql://localhost:3306/auction";
    String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    
   
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JToggleButton();
        account = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        acc_type = new javax.swing.JComboBox<>();
        pass1 = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        reset_Password = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("UserId");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 132, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        account.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        account.setText("don't have account");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Account Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, 30));

        acc_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acc_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Seller ", "Bidder" }));
        acc_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_typeActionPerformed(evt);
            }
        });
        getContentPane().add(acc_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 132, -1));

        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 132, -1));

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton1.setText("Back");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        reset_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset_Password.setText("Reset Password");
        reset_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_PasswordMouseClicked(evt);
            }
        });
        reset_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(reset_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_2_56_1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    private void acc_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_typeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

      
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        
       if(acc_type.getSelectedItem().toString().equals("Admin")){
        
            if(user_id.getText().equals("admin") && pass1.getText().equals("admin123")) {
            
                 JOptionPane.showMessageDialog(this, "Login Successfully");
                 new Admin_Dashboard().setVisible(true);
                 this.dispose();
            }
            else {
                  
                JOptionPane.showMessageDialog(this, "Please Enter correct UserId  & password");

            }
            
        } else {
        
            try {
                
                 con = DriverManager.getConnection(url,user,pass);
                 if(((String)acc_type.getSelectedItem()).equals("Bidder")){ 
                     
                     
                     
                    
                     st = con.prepareStatement("select * from bidder where UserId='"+user_id.getText()+"' and Password='"+pass1.getText()+"'");
                     rs= (java.sql.ResultSet) st.executeQuery();
          
                     if(rs.next()){
                     
                        JOptionPane.showMessageDialog(this, "Login Successfully");
                         Bidder_Dashboard sf=new Bidder_Dashboard();
                         
                        sf.setVisible(true);
                        sf.userid(user_id.getText());
                        this.dispose();
                        
                     }  
                     else {
                
                      JOptionPane.showMessageDialog(this, "Please Enter correct UserId  & password");

                      }
                 }  
                 else             
                 {
                     
                     st = con.prepareStatement("select * from seller where UserId='"+user_id.getText()+"' and Password='"+pass1.getText()+"'");
                     rs= (java.sql.ResultSet) st.executeQuery();
          
                     if(rs.next()){
                     
                        JOptionPane.showMessageDialog(this, "Login Successfully");
                       
                        Seller sf=new Seller();
                         
                        sf.setVisible(true);
                        sf.userid(user_id.getText());
                        this.dispose();

                      }  
                      else {
                
                      JOptionPane.showMessageDialog(this, "Please Enter correct UserId  & password");

                  }
                 }
               
                
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

            
        }
       
        
        
       
        
        
    }//GEN-LAST:event_loginMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:
        
        new Registration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        
         new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void reset_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_PasswordMouseClicked
       new Reset_Password().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_reset_PasswordMouseClicked

    private void reset_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acc_type;
    private javax.swing.JToggleButton account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton login;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JToggleButton reset_Password;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
