/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;

import com.mysql.cj.xdevapi.Statement;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author AMAN KUMAR
 */
public class Manage_Categories extends javax.swing.JFrame {

    String user="root";
    String url="jdbc:mysql://localhost:3306/auction";
    String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    
    /**
     * Creates new form Manage_Categories
     */
    public Manage_Categories() {
        initComponents();
        show_product();
    }

    public ArrayList<Product> productList(){
        ArrayList<Product> productList= new ArrayList<>();
        try{
            
              con = DriverManager.getConnection(url,user,pass);
            
          String sql = "Select * from product";   
            PreparedStatement st=(PreparedStatement)con.prepareStatement(sql);
           //Statement stmt=(Statement) con.createStatement();
           rs= st.executeQuery(sql);    
          
           Product product;
           while(rs.next())
           {
               product =new Product(rs.getString("Category"),rs.getString("ProductId"),rs.getString("ProductName"));
               productList.add(product);
           }
            con.close();
            
        }
        catch(Exception e)
        {
                        JOptionPane.showMessageDialog(null,e);
        }
        return productList;
    } 
    
    public void show_product()
    {
        ArrayList<Product> list = productList();
        DefaultTableModel model= (DefaultTableModel)product_table.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getCategory();
            row[1]=list.get(i).getProductId();
            row[2]=list.get(i).getProductName();
            model.addRow(row);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        view_product = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("Back");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, -1, -1));

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Product Id", "Product Name"
            }
        ));
        jScrollPane1.setViewportView(product_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 610, 280));

        view_product.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        view_product.setText("View Product");
        view_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_productMouseClicked(evt);
            }
        });
        getContentPane().add(view_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manage  Categories");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_3_5_55.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:

        new Admin_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void view_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_productMouseClicked
      View_Product obj=new View_Product();
      
        int selectedRow = product_table.getSelectedRow(); // get selected row index
         DefaultTableModel model = (DefaultTableModel) product_table.getModel(); // get table model
        String id = model.getValueAt(selectedRow, 1).toString();
        obj.setVisible(true);
        try{
            con = DriverManager.getConnection(url,user,pass);
           
             st = con.prepareStatement("select * from product where ProductId='"+id+"'");
             rs = (java.sql.ResultSet) st.executeQuery();
         
              String category="";
               String product_id ="";
               String product_name="";
               String price="";
               String description="";
               Image im = null;
           while(rs.next())
           {
               category = rs.getString("Category");
               product_id = rs.getString("ProductId");
               product_name=rs.getString("ProductName");
               price=rs.getString("Amount");
               description=rs.getString("ProductInformation");
                byte[] img= rs.getBytes("ProductImage");
                ImageIcon image = new ImageIcon(img);
                im = image.getImage();
           }
             
        obj.productdata(category, product_id, product_name, price, description,im);
        this.dispose();
        }
        catch(Exception ex)
        {
                        JOptionPane.showMessageDialog(null,ex );

        }
    }//GEN-LAST:event_view_productMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable product_table;
    private javax.swing.JToggleButton view_product;
    // End of variables declaration//GEN-END:variables
}
