/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;


import com.mysql.cj.xdevapi.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.*;
/**
/**
 *
 * @author AMAN KUMAR
 */
public class Reset_Password extends javax.swing.JFrame {

      String user="root";
    String url="jdbc:mysql://localhost:3306/auction";
    String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    /**
     * Creates new form Reset_Password
     */
    public Reset_Password() {
        initComponents();
    }

     boolean checkpassword(String pwrd)
    {
       boolean flag_small=false;
       boolean flag_capital=false;
       boolean flag_int=false;
       
       if(pwrd.length()<8)return false;
       
       for(int i=0;i<pwrd.length();i++)
       {
           if(pwrd.charAt(i)>='a' && pwrd.charAt(i)<='z')
           {
               flag_small=true;
           }
           else if(pwrd.charAt(i)>='A' && pwrd.charAt(i)<='Z')
           {
               flag_capital=true;
           }
           else if(Character.isDigit(pwrd.charAt(i)))
           {
               flag_int=true;
           }
       }
        
       if( flag_small==true && flag_capital==true && flag_int==true)
       {
           return true;
       }
       return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Enter = new javax.swing.JToggleButton();
        Enter1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        acc_type = new javax.swing.JComboBox<>();
        Password_new = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enter UserId");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 120, 41));

        UserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIdActionPerformed(evt);
            }
        });
        getContentPane().add(UserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 130, 41));

        Enter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Enter.setText("Change Password");
        Enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterMouseClicked(evt);
            }
        });
        getContentPane().add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        Enter1.setText("Back");
        Enter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Enter1MouseClicked(evt);
            }
        });
        getContentPane().add(Enter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Account Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, 30));

        acc_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acc_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seller ", "Bidder", " " }));
        acc_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_typeActionPerformed(evt);
            }
        });
        getContentPane().add(acc_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 110, -1));
        getContentPane().add(Password_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Reset Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_2_27_56.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterMouseClicked
        
      try{
                 con = DriverManager.getConnection(url,user,pass);
                 if(((String)acc_type.getSelectedItem()).equals("Bidder"))
                 { 
                     
                       String user= UserId.getText();
                   String Password = Password_new.getText();
                   if(!Password.isEmpty() && checkpassword(Password)==true)
                   {
                       try{
                         PreparedStatement ps = con.prepareStatement("select * from bidder where UserId='"+user+"'");
                         ResultSet  rs = (java.sql.ResultSet) ps.executeQuery();
          
                          if(rs.next() == true){
                         String query="update bidder set Password='"+Password+"' where UserId='"+user+"'";
                         java.sql.Statement st;
                         st = con.createStatement();
                         st.executeUpdate(query);
                         JOptionPane.showMessageDialog(this,"password updated successfully");
                       }
                  else
                     JOptionPane.showMessageDialog(this,"Please Enter Valid User Name");  
         
                       }
                   catch(SQLException ex)
                   {
                       Logger.getLogger(Logger.class.getName()).log(Level.SEVERE, null, ex);
             
                   }
                   }
                   else
                   {
                       JOptionPane.showMessageDialog(this,"New Password is not correct");
                   }
                    
                 }  
                 else             
                 {
                     
                        String user= UserId.getText();
                        String Password = Password_new.getText();
                     if(!Password.isEmpty() && checkpassword(Password)==true)
                   {    
                     try{
                            PreparedStatement ps = con.prepareStatement("select * from seller where UserId='"+user+"'");
                            ResultSet  rs = (java.sql.ResultSet) ps.executeQuery();
                          if(rs.next() == true){
                            String query="update seller set Password='"+Password+"' where UserId='"+user+"'";
                           java.sql.Statement st;
                            st = con.createStatement();
                            st.executeUpdate(query);
                           JOptionPane.showMessageDialog(this,"password updated successfully");
                            }
                          else
                            JOptionPane.showMessageDialog(this,"Please Enter Valid User Name");  
                         }
                     catch(SQLException ex)
                         {
                           Logger.getLogger(Logger.class.getName()).log(Level.SEVERE, null, ex);
             
                         }
                 }
                      
                   else
                   {
                       JOptionPane.showMessageDialog(this,"New Password is not correct");
                   }
                 }
            }
          catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Please Enter Right Credentials");
            }

    
    }//GEN-LAST:event_EnterMouseClicked

    private void acc_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_typeActionPerformed

    private void Enter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Enter1MouseClicked

new Login().setVisible(true);
this.dispose();
    }//GEN-LAST:event_Enter1MouseClicked

    private void UserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Enter;
    private javax.swing.JToggleButton Enter1;
    private javax.swing.JPasswordField Password_new;
    private javax.swing.JTextField UserId;
    private javax.swing.JComboBox<String> acc_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
