/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author AMAN KUMAR
 */
public class View_Product extends javax.swing.JFrame {

    
    String user="root";
    String url="jdbc:mysql://localhost:3306/auction";
    String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    
    
    /**
     * Creates new form View_Product
     */
    public View_Product() {
        initComponents();
        
    }
    
    void productdata(String Category,String ProductId,String ProductName,String Price,String info,Image im)
    {
        category1.setText(Category);
        productid1.setText(ProductId);
        productname1.setText(ProductName);
        amt.setText(Price);
        description1.setText(info);
         Image myimg= im.getScaledInstance(img1.getWidth(),img1.getHeight(),Image.SCALE_SMOOTH);
         ImageIcon newImage= new ImageIcon(myimg);
         img1.setIcon(newImage);
            
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update = new javax.swing.JToggleButton();
        img1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        product_id = new javax.swing.JLabel();
        product_name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        category = new javax.swing.JLabel();
        category_combo = new javax.swing.JComboBox<>();
        category1 = new javax.swing.JTextField();
        productid1 = new javax.swing.JLabel();
        productname1 = new javax.swing.JLabel();
        amt = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        img1.setText(".");
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 193, 236));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Product Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Product Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Product Decription");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));
        getContentPane().add(product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(2478, 76, -1, -1));
        getContentPane().add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(2478, 113, -1, -1));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 546, -1, 16));
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 805, 82, -1));

        jToggleButton1.setText("Back");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, -1, -1));
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 70, -1, -1));

        category_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Grocery", "Furniture", "Stationary", "Textiles", "Jewelry", "Sports" }));
        getContentPane().add(category_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 189, -1));

        category1.setText("jTextField1");
        getContentPane().add(category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, -1));

        productid1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productid1.setText("jLabel1");
        getContentPane().add(productid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        productname1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productname1.setText("jLabel1");
        getContentPane().add(productname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        amt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        amt.setText("jLabel1");
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        description1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description1.setText("jLabel1");
        description1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(description1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 200, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_3_5_55.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked

        try {
            // TODO add your handling code here:
        
            con = DriverManager.getConnection(url,user,pass);
            
            String sql = "UPDATE product set Category = ? where ProductId='" + productid1.getText() +"'";   
            PreparedStatement st=(PreparedStatement)con.prepareStatement(sql);
       
            st.setString(1,(String)category_combo.getSelectedItem());
            
            category1.setText((String)category_combo.getSelectedItem());
             st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product updated Successfully");
            con.close();
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_updateMouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:

        new Manage_Categories().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amt;
    private javax.swing.JLabel category;
    private javax.swing.JTextField category1;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JLabel description;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel product_id;
    private javax.swing.JLabel product_name;
    private javax.swing.JLabel productid1;
    private javax.swing.JLabel productname1;
    private javax.swing.JToggleButton update;
    // End of variables declaration//GEN-END:variables
}
