/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package online.auction.site;

import com.mysql.cj.xdevapi.Statement;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AMAN KUMAR
 */
public class Winner_declaring extends javax.swing.JFrame {

     String user="root";
     String url="jdbc:mysql://localhost:3306/auction";
     String pass="99Aman*kr";
    
    Connection con = null;
    PreparedStatement st = null;
    ResultSet rs = null;
    
    /**
     * Creates new form Winner_declaring
     */
    public Winner_declaring() {
        initComponents();
        show_winners();
    }
    public void search(String str)
    {
        DefaultTableModel model = (DefaultTableModel)winning_table.getModel();
        TableRowSorter<DefaultTableModel> trs= new TableRowSorter<>(model);
        winning_table.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        double Hprice=0;
        String winnerId = "";
    for (int i = 0; i < winning_table.getRowCount(); i++) {
    int modelIndex = trs.convertRowIndexToModel(i);
    int  value = Integer.parseInt( winning_table.getModel().getValueAt(modelIndex, 4).toString());
    if (value > Hprice) {
        Hprice = value;
        winnerId=winning_table.getModel().getValueAt(modelIndex, 2).toString();
    }
}
   
          Winner_Id_1.setText(winnerId);
            Price_max.setText(Hprice+"");

    }
                                     

    public ArrayList<Winner> winnerslist(){
        ArrayList<Winner> winnerslist= new ArrayList<>();
        try{
            
              con = DriverManager.getConnection(url,user,pass);
            
                String sql = "Select * from winner";   
            PreparedStatement st=(PreparedStatement)con.prepareStatement(sql);
           rs= st.executeQuery(sql);    
          
           Winner winners_1;
           while(rs.next())
           {
               winners_1 =new Winner(rs.getString("Product_Id"),rs.getString("ProductName"),rs.getString("Bidder_Id"),rs.getString("Seller_Id"),rs.getString("Bidding_Amount"));
               winnerslist.add(winners_1);
           }
            con.close();
            
        }
        catch(Exception e)
        {
                        JOptionPane.showMessageDialog(null,e);
        }
        return winnerslist;
    } 
    
    public void show_winners()
    {
        
        ArrayList<Winner> list = winnerslist();
        DefaultTableModel model= (DefaultTableModel)winning_table.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getProductId();
            row[1]=list.get(i).getProductName();
            row[2]=list.get(i).getBidder_Id();
            row[3]=list.get(i).getSeller_Id();
            row[4]=list.get(i).getAmount();
//            if(Hprice < Integer.parseInt(list.get(i).getAmount()))
//                {
//                    Hprice = Integer.parseInt(list.get(i).getAmount());
//                    winnerId = list.get(i).getBidder_Id();
//                }
            model.addRow(row);
        }
//            Winner_Id_1.setText(winnerId);
//            Price_max.setText(Hprice+"");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        winning_table = new javax.swing.JTable();
        search_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Winner_Id_1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Price_max = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winning_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Bidder Id", "Seller Id", "Amount"
            }
        ));
        winning_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winning_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(winning_table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 600, 243));

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_fieldKeyReleased(evt);
            }
        });
        getContentPane().add(search_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 89, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Search(Product Name)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Winner");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 68, 25));

        Winner_Id_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Winner_Id_1.setText(".");
        getContentPane().add(Winner_Id_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 89, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        Price_max.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Price_max.setText(".");
        getContentPane().add(Price_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Winner Status");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 196, 36));

        jToggleButton1.setText("Back");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/auction/site/fotor_2023-3-21_3_5_55.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void winning_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winning_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_winning_tableMouseClicked

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void search_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyReleased
        String searchstring =search_field.getText();
        search(searchstring);
//          int Hprice=0;
//               String winnerName = "";
//               DefaultTableModel tableModel;
//               tableModel=(DefaultTableModel) winning_table.getModel(); 
//                int rows = tableModel.getRowCount(); 
//                for(int i = rows - 1; i >=0; i--)
//                {
//                   tableModel.removeRow(i); 
//                }
//            try {
//              con = DriverManager.getConnection(url,user,pass);
//   
//                PreparedStatement st=con.prepareStatement("SELECT Product_Id,ProductName,, usr.email, usr.phone, bd.price from product as pdt inner join bidding as bd inner join userdb as usr on pdt_id='"+pdtId.getSelectedItem().toString()+"' and productId='"+pdtId.getSelectedItem().toString()+"' and bidderId=userName ");
//                   
//                ResultSet rss = (java.sql.ResultSet) st.executeQuery();
//            while(rss.next())
//            {
////                category, subcategory, pdt_id, pdt_name, brand, pdt_info, price
//                String ProductName=rss.getString("pdt_name");
//                String firstName=rss.getString("firstName");
//                String lastName=rss.getString("lastName");
//                String BidderName = firstName+" "+lastName;
//                String email=rss.getString("email");
//                
//                String Phone=rss.getString("phone");
//                
//                String Price=rss.getString("price");
//                if(Hprice < Integer.parseInt(Price))
//                {
//                    Hprice = Integer.parseInt(Price);
//                    winnerName = BidderName;
//                }
//                String tableData[]={ProductName, BidderName, email, Phone, Price};
//                
//                tableModel.addRow(tableData);
//            }
//            winner.setText(winnerName);
//            price.setText(Hprice+"");
//        } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(RemoveProduct.class.getName()).log(Level.SEVERE, null, ex);
//        }
      
    }//GEN-LAST:event_search_fieldKeyReleased

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
         new Admin_Dashboard().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jToggleButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Winner_declaring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Winner_declaring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Winner_declaring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Winner_declaring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Winner_declaring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price_max;
    private javax.swing.JLabel Winner_Id_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField search_field;
    private javax.swing.JTable winning_table;
    // End of variables declaration//GEN-END:variables
}
